name: jmap
description: A minimal library to work with JSON decoded maps and lists in a type-safe way.
version: 1.1.0
homepage: https://github.com/mgenware/jmap

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  mgenware_dart_lints: ^1.0.0
  test: ^1.16.0
