name: jmap
description: A minimal library to work with JSON decoded maps and lists in a type-safe way.
version: 1.3.0
homepage: https://github.com/mgenware/jmap

environment:
  sdk: ">=2.13.0 <4.0.0"

dev_dependencies:
  mgenware_dart_lints: ^4.1.0
  test: ^1.16.0
