name: jmap
description: A minimal library to work with JSON decoded maps and lists in a type-safe way.
version: 3.1.1
homepage: https://github.com/mgenware/jmap

environment:
  sdk: ">=2.13.0 <4.0.0"

dev_dependencies:
  mgenware_dart_lints: ^6.5.2
  test: ^1.16.0
dependencies:
  collection: ^1.19.0
